// Copyright 2024-2026 Andrey Vasilevsky <anvanster@gmail.com>
// SPDX-License-Identifier: Apache-2.0

//! Embedded authorship and project metadata.
//!
//! These constants are compiled into the binary and can be used
//! to display version and authorship information at runtime.
//!
//! Includes build-time provenance: git hash, build timestamp, and
//! rustc version — embedded via `build.rs` at compile time.

/// The author of codegraph.
pub const AUTHOR: &str = "Andrey Vasilevsky <anvanster@gmail.com>";

/// The project's SPDX license identifier.
pub const LICENSE: &str = "Apache-2.0";

/// The project's source repository URL.
pub const REPOSITORY: &str = "https://github.com/anvanster/codegraph";

/// The crate version, pulled from Cargo.toml at compile time.
pub const VERSION: &str = env!("CARGO_PKG_VERSION");

/// The crate name, pulled from Cargo.toml at compile time.
pub const NAME: &str = env!("CARGO_PKG_NAME");

// Build-time provenance generated by build.rs
include!(concat!(env!("OUT_DIR"), "/build_info.rs"));

/// Print a formatted summary of project metadata to stdout.
pub fn print_metadata() {
    println!("{} v{} ({})", NAME, VERSION, GIT_HASH_SHORT);
    println!("Author: {}", AUTHOR);
    println!("License: {}", LICENSE);
    println!("Repository: {}", REPOSITORY);
    println!("Built: {} with {}", BUILD_TIMESTAMP, RUSTC_VERSION);
}

/// Return a formatted summary of project metadata as a `String`.
pub fn metadata_string() -> String {
    format!(
        "{name} v{version} ({git})\n\
         Author: {author}\n\
         License: {license}\n\
         Repository: {repo}\n\
         Built: {timestamp} with {rustc}",
        name = NAME,
        version = VERSION,
        git = GIT_HASH_SHORT,
        author = AUTHOR,
        license = LICENSE,
        repo = REPOSITORY,
        timestamp = BUILD_TIMESTAMP,
        rustc = RUSTC_VERSION,
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn author_constant_names_the_maintainer() {
        assert_eq!(AUTHOR, "Andrey Vasilevsky <anvanster@gmail.com>");
    }

    #[test]
    fn license_is_apache_2_0() {
        assert_eq!(LICENSE, "Apache-2.0");
    }

    #[test]
    fn repository_points_at_github() {
        assert_eq!(REPOSITORY, "https://github.com/anvanster/codegraph");
        assert!(REPOSITORY.starts_with("https://"));
    }

    #[test]
    fn version_and_name_are_populated_from_cargo() {
        // Both are env!()-derived, so they must be non-empty at compile time.
        assert!(!VERSION.is_empty());
        assert!(!NAME.is_empty());
        assert_eq!(NAME, "codegraph");
    }

    #[test]
    fn build_info_constants_are_present() {
        // build.rs always writes these constants (falling back to "unknown"),
        // so they are guaranteed non-empty.
        assert!(!GIT_HASH.is_empty());
        assert!(!GIT_HASH_SHORT.is_empty());
        assert!(!RUSTC_VERSION.is_empty());
        assert!(!BUILD_TIMESTAMP.is_empty());
    }

    #[test]
    fn metadata_string_has_five_lines() {
        let s = metadata_string();
        assert_eq!(s.lines().count(), 5);
    }

    #[test]
    fn metadata_string_embeds_every_field() {
        let s = metadata_string();
        assert!(s.contains(NAME));
        assert!(s.contains(VERSION));
        assert!(s.contains(GIT_HASH_SHORT));
        assert!(s.contains(AUTHOR));
        assert!(s.contains(LICENSE));
        assert!(s.contains(REPOSITORY));
        assert!(s.contains(BUILD_TIMESTAMP));
        assert!(s.contains(RUSTC_VERSION));
    }

    #[test]
    fn metadata_string_uses_the_expected_labels() {
        let s = metadata_string();
        assert!(s.contains("Author: "));
        assert!(s.contains("License: "));
        assert!(s.contains("Repository: "));
        assert!(s.contains("Built: "));
        // The first line carries the "name vVERSION (git)" header shape.
        let first = s.lines().next().unwrap();
        assert!(first.starts_with(&format!("{NAME} v{VERSION} (")));
        assert!(first.ends_with(')'));
    }
}
